# Generated by Django 4.2.7 on 2023-12-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='user',
            new_name='user_id',
        ),
    ]
