# Generated by Django 4.2.7 on 2023-12-03 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_user_userinformation_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='user_id',
            new_name='user',
        ),
    ]
