# Generated by Django 4.2.7 on 2023-12-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_user_id_userinformation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='profilFotografi',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
