# Generated by Django 4.2.7 on 2023-12-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_userinformation_profilfotografi'),
    ]

    operations = [
        migrations.AddField(
            model_name='danisan',
            name='istek',
            field=models.CharField(choices=[('KA', 'Kilo Aldırma'), ('KV', 'Kilo Verdirme'), ('KK', 'Kilo Koruma'), ('KKA', 'Kas Kazandırma')], max_length=3, null=True),
        ),
    ]
