# Generated by Django 4.2.7 on 2023-12-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_eslesme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eslesme',
            old_name='antrenor_id',
            new_name='antrenor',
        ),
        migrations.RenameField(
            model_name='eslesme',
            old_name='danisan_id',
            new_name='danisan',
        ),
    ]
