# Generated by Django 4.2.7 on 2023-12-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_rename_antrenor_id_eslesme_antrenor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eslesme',
            name='antrenor',
            field=models.IntegerField(),
        ),
    ]
