# Generated by Django 4.2.7 on 2023-12-04 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_eslesme_antrenor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eslesme',
            name='danisan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.danisan'),
        ),
    ]
