# Generated by Django 4.2.7 on 2023-12-04 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0012_alter_eslesme_danisan'),
    ]

    operations = [
        migrations.CreateModel(
            name='danisan_kayitlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('kilo', models.FloatField()),
                ('vucutYagOrani', models.FloatField()),
                ('kasKutlesi', models.FloatField()),
                ('vucutKitleIndeksi', models.FloatField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
