# Generated by Django 4.2.7 on 2023-12-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_danisan_kayitlari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eslesme',
            name='danisan',
            field=models.IntegerField(),
        ),
    ]
