# Generated by Django 4.2.7 on 2023-12-05 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0016_beslenme_planlari_antrenor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='egzersiz_beslenme_planlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('istek', models.CharField(choices=[('KA', 'Kilo Aldırma'), ('KV', 'Kilo Verdirme'), ('KK', 'Kilo Koruma'), ('KKA', 'Kas Kazandırma')], max_length=3, null=True)),
                ('egzersiz_content', models.TextField()),
                ('beslenme_content', models.TextField()),
                ('antrenor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='egzersiz_planlari',
            name='antrenor',
        ),
        migrations.DeleteModel(
            name='beslenme_planlari',
        ),
        migrations.DeleteModel(
            name='egzersiz_planlari',
        ),
    ]
