# Generated by Django 4.2.7 on 2023-12-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_egzersiz_beslenme_planlari_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan_eslesme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antrenor', models.CharField(max_length=3)),
                ('plan_id', models.CharField(max_length=3)),
                ('danisan', models.CharField(max_length=3)),
            ],
        ),
    ]
