# Generated by Django 4.2.7 on 2023-12-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_plan_eslesme'),
    ]

    operations = [
        migrations.AddField(
            model_name='egzersiz_beslenme_planlari',
            name='baslik',
            field=models.TextField(default=' '),
        ),
    ]
